language: ruby
sudo: false
cache: bundler
rvm:
- 2.3.1
before_script:
- chmod +x ./scripts/cibuild
script: "./scripts/cibuild"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  email: false
  slack:
    secure: HeG0Xoi1sx6jWTdlXgDXREQOQHBAlcNBxoMZkrSZ/w8nlfA7TvZQx8A1XQLzHhwVmTwptxIUDV0lPt35W12hoJtA0WriLjzjCFj/xpGQ6K2uXRw3ZONkS5lwHMlVn796m5b0EjBA0+grSF9g8pa0B1gxd/Cq4aTeBmA8gfPKstQ=
