language: ruby
sudo: false
cache: bundler
rvm:
- 2.1

before_script:
 - chmod +x ./scripts/cibuild # or do this locally and commit

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./script/cibuild

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
