#!/usr/bin/env bash
set -e # halt script on error

echo 'Testing travis...'
bundle exec travis-lint
bundle exec jekyll build
bundle exec htmlproofer --url-ignore https://veertu.com/ --http-status-ignore 403, ./_site
